### ISSUE TITLE
`signin` is not fired when logging in via token

### ISSUE THREAD

**Issue by rmehner** [hoodiehq/hoodie-account-client#144]
# How to reproduce

1. Create account for user via `hoodie-account-server`
2. Add login token for user on server:

```js
api.account({username: username}).tokens.add({
  id: 'MY_SECRET_TOKEN',
  type: 'login',
  recipient: username,
  timeout: 7200 // 2h
})
```

3. On the client, register for events:

```js
account.on('signin', () => console.log('sign in, woop!'))
```

4. Sign in via `hoodie-account-client`

```js
account.signIn({
  username: username,
  token: 'MY_SECRET_TOKEN'
})
```

# Expected behaviour

1. User is signed in.
2. See `sign in, woop!` in the console.

# Actual behaviour

1. User is signed in.
2. See nothing in the console.

Note: the event `reauthenticate` is fired after a sign in, which I currently use a workaround :)

**Comment by gr2m** [comment]
for anyone who wants to work on this. I’m very confident the problem is in this line:
https://github.com/hoodiehq/hoodie-account-client/blob/69cd117f64435921619c8018e7fcd52a03e9a9f3/lib/sign-in.js#L45

It returns true because both `get(state, 'account.username')` and `options.username` are undefined. We should add an additional check if `get(state, 'account.username')` returns undefined we should always emit `signin`, because it means the user is currently not signed in.

While at it, we shouldn’t compare to `options.username` but to `data.account.username` which is what the server returns. That will correctly trigger a `reauthenticate` event for a user that is already signed in and reauthenticates using a token, not username & password

**Comment by gr2m** [comment]
Actually, we should not compare usernames at all :) Instead, we should compare the user account id. So the if block would look something like this

```js
if (state.account.id === data.account.id) {
  emitEvent = 'reauthenticate'
}
```

Because for one not all user accounts will have usernames and besides that a username could have changed, but we would still like a user to reauthenticate

**Comment by sohini-roy** [comment]
thank you for the description. it was very helpful :)
i would love to work on this issue

**Comment by gr2m** [comment]
done via https://github.com/hoodiehq/hoodie-account-client/issues/157
